<?php

namespace ImageBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository as EntityRepository;

class SlideRepository extends EntityRepository implements SlideInterface
{
    /**
     * {@inheritdoc}
     **/
    public function getSlides() {
        $now = (new \DateTime())->format('Y-m-d h:i:s');
        $slides = $this->createQueryBuilder('o')
            ->andWhere('o.enabled = :enabled')    
            ->andWhere('o.date_start <= :now and o.date_finish >= :now')
                
            ->setParameter('enabled', 'true')
            ->setParameter('now', $now)
            ->orderBy('o.position', 'ASC')
            ->addOrderBy('o.updatedAt', 'DESC')
                
            ->getQuery()
            ->getResult()
        ;
        return $slides;        
    }

}
