image_admin_slide:
    prefix: /admin
    resource: |
        alias: image.slide
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: image_admin
        vars:
            index:
                icon: 'icon newspaper'
    type: sylius.resource
    
image_admin_slide_update:
    path: /admin/slides/{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: image.controller.slide:updateAction
        _sylius:
            section: admin
            permission: true
            template: ImageBundle::update.html.twig
            redirect: image_admin_slide_update