services:
    report.listener.admin.menu_builder:
        class: ReportBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    report.controller:
        class: ReportBundle\Controller\ReportController
        arguments: ['@templating']

    report.income.form.type:
        class: ReportBundle\Form\Type\IncomeType
        tags:
            - { name: form.type, alias: report_income}

    report.income.form:
      class: Symfony\Component\Form\Form
      factory: ["@form.factory", createNamed]
      arguments:
        - 'report_income'
        - 'ReportBundle\Form\Type\IncomeType'

    report.provider.income:
        class: ReportBundle\Provider\IncomeProvider

    report.grossProfit.form:
          class: Symfony\Component\Form\Form
          factory: ["@form.factory", createNamed]
          arguments:
            - 'gross_profit'
            - 'ReportBundle\Form\Type\GrossProfitType'

    report.provider.grossProfit:
        class: ReportBundle\Provider\GrossProfitProvider

    report.commodityBalance.form:
          class: Symfony\Component\Form\Form
          factory: ["@form.factory", createNamed]
          arguments:
            - 'gross_profit'
            - 'ReportBundle\Form\Type\CommodityBalanceType'

    report.provider.commodityBalance:
        class: ReportBundle\Provider\CommodityBalanceProvider