sylius_admin_order_restore:
    path: /orders/{id}/restore
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:changeAllOrderStatus
        _sylius:
            state_machine:
                graph: sylius_order
                transition: restore
            redirect: referer
            
sylius_admin_order_recancel:
    path: /orders/{id}/recancel
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:changeAllOrderStatus
        _sylius:
            state_machine:
                graph: sylius_order
                transition: recancel
            redirect: referer            