services:
    order.listener.admin.menu_builder:
        class: Override\OrderBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    order.listener.admin.order.show.menu_builder:
        class: Override\OrderBundle\Menu\AdminOrderShowMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.order.show, method: addAdminOrderShowMenuItems }
    order.grid.filter.states:
            class: Override\OrderBundle\Grid\Filter\StateMachineFilter
            tags:
                -
                    name: sylius.grid_filter
                    type: states
                    form_type: Override\OrderBundle\Form\Type\Filter\StateMachineFilterType