# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "config.yml" }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            max_files: 7
