sylius_resource:
    resources:
        app.news:
            driver: doctrine/orm
            classes:
                model: Marinewool\StaticBundle\Entity\News
        app.static_content:
            driver: doctrine/orm
            classes:
                model: Marinewool\StaticBundle\Entity\StaticContent