sylius_grid:
    grids:
        image_admin:
            driver:
                name: doctrine/orm
                options:
                    class: Marinewool\ImageBundle\Entity\Slide
            limits: [15, 30, 45, 100]
            fields:
                description:
                    type: string
                    label: sylius.ui.description                
                    position: 0
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: true
                    position: 1
                date_start:
                    type: datetime
                    label: sylius.ui.start_date
                    sortable: true
                    position: 2
                date_finish:
                    type: datetime
                    label: sylius.ui.end_date
                    sortable: true
                    position: 3
                enabled:
                    type: twig
                    label: sylius.ui.is_enabled
                    position: 4
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete