parameters:
    image.model.slide.class: Marinewool\ImageBundle\Entity\Slide
    image.model.slide_image.class: Marinewool\ImageBundle\Entity\SlideImage
services:
    image.utils:
        class: Marinewool\ImageBundle\Utils\ImageUtils
        
    image.listener.admin.menu_builder:
        class: Marinewool\ImageBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    
    image.slide.form.type:
        class: Marinewool\ImageBundle\Form\Type\SlideType
        arguments: ['%image.model.slide.class%', ['sylius']]
        tags:
            - { name: form.type}
    image.slide_image.form.type:
            class: Marinewool\ImageBundle\Form\Type\SlideImageType
            tags:
                - { name: form.type }
            arguments: ['%image.model.slide_image.class%']
    sylius.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        arguments: ['@sylius.image_uploader']
        tags:
            - { name: kernel.event_listener, event: "sylius.product.pre_create", method: "uploadImages" }
            - { name: kernel.event_listener, event: "sylius.product.pre_update", method: "uploadImages" }
            - { name: kernel.event_listener, event: "sylius.taxon.pre_create", method: "uploadImages" }
            - { name: kernel.event_listener, event: "sylius.taxon.pre_update", method: "uploadImages" }
            - { name: kernel.event_listener, event: "image.slide.pre_create", method: "uploadImages" }
            - { name: kernel.event_listener, event: "image.slide.pre_update", method: "uploadImages" }            