ImageBundle\Entity\Slide:
    properties:
        url:
            - NotBlank:
                groups: [sylius]
        alt:
            - NotBlank:
                groups: [sylius]
        description:
            - NotBlank:
                groups: [sylius]
        position:
            - NotBlank:
                groups: [sylius]
        date_start:
            - NotBlank:
                groups: [sylius]
        date_finish:
            - NotBlank:
                groups: [sylius]
        enabled:
            - NotBlank:
                groups: [sylius]
        images:
            - Valid: ~

        