liip_imagine:
    filter_sets:
        image_bundle_slide_normal:
            quality : %liip_quality%
            filters:
                thumbnail: { size: [700, 300], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: %liip_quality%, progressive: true } 