ImageBundle\Entity\Slide:
    properties:
        url:
            - NotBlank: ~
        alt:
            - NotBlank: ~
        description:
            - NotBlank: ~
        position:
            - NotBlank: ~
        date_start:
            - NotBlank: ~
        date_finish:
            - NotBlank: ~
        enabled:
            - NotBlank: ~
        