IntegrationBundle\Model\Product:
  xml_root_name: product
  accessor_order: custom
  custom_accessor_order: [taxon, taxonName, id, id1c, name, isSimple, shortDescription, attributes, productVariants]
  properties:
    id:
      expose: true
      type: integer
    id_1c:
      expose: true
      type: string
      serialized_name: id1c
      xml_element:
        cdata: false
    name:
      expose: true
      type: string
      xml_element:
        cdata: false
    isSimple:
      expose: true
      type: boolean
    taxon:
      expose: true
      type: integer
    taxonName:
      expose: true
      type: string
      xml_element:
        cdata: false
    description:
      expose: true
      type: string
      xml_element:
        cdata: false
    shortDescription:
      expose: true
      type: string
      xml_element:
        cdata: false
    productVariants:
      expose: true
      type: array<IntegrationBundle\Model\ProductVariant>
      xml_list:
        inline: false
        entry_name: productVariant
    price:
      expose: true
      type: integer
    onHand:
      expose: true
      type: integer
    attributes:
      expose: true
      type: array<IntegrationBundle\Model\Attribute>
      xml_list:
        inline: false
        entry_name: attribute
