IntegrationBundle\Model\ProductVariant:
  xml_root_name: product_variant
  accessor_order: custom
  custom_accessor_order: [id, id1c, name, originalPrice, priceRegular, onHand]
  properties:
    id:
      type: integer
    id1c:
      type: string
      serialized_name: id1c
      xml_element:
        cdata: false
    name:
      type: string
      xml_element:
        cdata: false
    priceRegular:
      type: integer
    pricePromotion:
      type: integer
    originalPrice:
      type: integer
    onHand:
      type: integer
