IntegrationBundle\Model\OrderItem:
  xml_root_name: order
  accessor_order: custom
  custom_accessor_order: [productId, productId1c, variantId, variantId1c, quantity, price]
  properties:
    productId:
      type: integer
    productId1c:
      type: string
      xml_element:
        cdata: false
    variantId:
      type: integer
    variantId1c:
      type: string
      xml_element:
        cdata: false
    quantity:
      type: integer
    price:
      type: integer