IntegrationBundle\Model\Customer:
  xml_root_name: customer
  accessor_order: custom
  custom_accessor_order: [id, id1c, firstName, lastName]
  properties:
    id:
      type: integer
    id1c:
      type: string
      serialized_name: id1c
      xml_element:
        cdata: false
    email:
      type: string
      xml_element:
        cdata: false
    firstName:
      type: string
      xml_element:
        cdata: false
    lastName:
      type: string
      xml_element:
        cdata: false
    birthday:
      type: DateTime<"Y-m-d">
      xml_element:
        cdata: false
    gender:
      type: string
      xml_element:
        cdata: false
    phoneNumber:
      type: string
      xml_element:
        cdata: false
