IntegrationBundle\Model\Product:
  xml_root_name: product
  accessor_order: custom
  custom_accessor_order: [taxon, taxonName, id, id1c, name, isSimple, shortDescription, attributes, productVariants]
  properties:
    id:
      type: integer
    id1c:
      type: string
      serialized_name: id1c
      xml_element:
        cdata: false
    name:
      type: string
      xml_element:
        cdata: false
    isSimple:
      type: boolean
    taxon:
      type: integer
    taxonName:
      type: string
      xml_element:
        cdata: false
    description:
      type: string
      xml_element:
        cdata: false
    shortDescription:
      type: string
      xml_element:
        cdata: false
    productVariants:
      type: array<IntegrationBundle\Model\ProductVariant>
      xml_list:
        inline: false
        entry_name: productVariant
    priceRegular:
      type: integer
    pricePromotion:
      type: integer
    originalPrice:
      type: integer
    onHand:
      type: integer
    attributes:
      type: array<IntegrationBundle\Model\Attribute>
      xml_list:
        inline: false
        entry_name: attribute