IntegrationBundle\Model\Attribute:
  exclusion_policy: ALL
  xml_root_name: attribute
  accessor_order: custom
  custom_accessor_order: [name, value]
  properties:
    name:
      type: string
      xml_element:
        cdata: false
    value:
      type: string
      xml_element:
        cdata: false