income_show:
    path: /income/
    methods: [GET, POST]
    defaults:
        _controller: report.controller:incomeAction
gross_profit_show:
    path: /gross_profit/
    methods: [GET, POST]
    defaults:
        _controller: report.controller:grossProfitAction
commodity_balance_show:
    path: /commodity_balance/
    methods: [GET, POST]
    defaults:
        _controller: report.controller:commodityBalanceAction