services:
    app.listener.admin.menu_builder:
        class: AppBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    app.listener.admin.order.show.menu_builder:
        class: AppBundle\Menu\AdminOrderShowMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.order.show, method: addAdminOrderShowMenuItems }
    app.updater_version:
        class: AppBundle\Utils\UpdaterAssetsVersion
    app.sitemap_provider.static_content:
        class: AppBundle\Provider\StaticContentUrlProvider
        tags:
            - { name: sylius.sitemap_provider }
        arguments:
            - '@app.repository.static_content'
            - '@router'
            - '@sylius.sitemap_url_factory'
            - '@sylius.locale_provider'
    app.grid.filter.states:
            class: AppBundle\Grid\Filter\StateMachineFilter
            tags:
                -
                    name: sylius.grid_filter
                    type: states
                    form_type: AppBundle\Form\Type\Filter\StateMachineFilterType