sylius_grid:
    grids:
        app_admin_news:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\News
            limits: [15, 30, 45, 100]
            fields:
                short_text:
                    type: string
                    label: sylius.ui.description                
                    position: 1
                header:
                    type: string
                    label: app.ui.header
                    sortable: true
                    position: 0
                created_at:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: true
                    position: 2
                updated_at:
                    type: datetime
                    label: sylius.ui.updated
                    sortable: true
                    position: 3
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                header:
                    type: string
                    label: app.ui.header