services:
    integration.controller.customer:
        class: IntegrationBundle\Controller\CustomerIntegrationController

    integration.controller.product:
        class: IntegrationBundle\Controller\ProductIntegrationController

    integration.factory:
        class: IntegrationBundle\Model\Factory
        arguments:
            - "@doctrine.orm.entity_manager"

    integration.repository:
        class: IntegrationBundle\Repository\IntegrationRepository
        arguments:
            - "@integration.factory"